schoolstore/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('cart',views.cart_book,name='cart_book'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')

]

schoolstore/dropdownapp/urls.py
from django.urls import path
from . import views

app_name='dropdownapp'

urlpatterns = [
    path('', views.getdata, name="getdata"),
]

schoolstore/loginapp/urls.py
from . import views
from django.urls import path
app_name='loginapp'
urlpatterns = [

    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('loggedin',views.loggedin,name='loggedin'),
    path('details',views.details,name='details'),
    path('order',views.order,name='order'),




]

schoolstore/schoolapp/urls.py
from django.urls import path
from . import views
app_name='schoolapp'
urlpatterns = [


    # path('',views.home,name='home'),
    path('',views.allStream,name='allStream'),
    path('<slug:c_slug>/',views.allStream,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.prodDetail, name='prodCatdetail')






]

schoolstore/schoolstore/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schoolapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('loginapp/', include('loginapp.urls')),
    path('dropdownapp',include('dropdownapp.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

schoolstore/cart/models.py
from django.db import models

# Create your models here.
from django.db import models
from schoolapp.models import Product
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.fees * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

# Create your models here.

schoolstore/cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from schoolapp.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.seats:
          cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        # cart_items=CartItem.objects.filter(cart=cart,active=True)
        # for cart_item in cart_items:
        #     total +=(cart_item.product.fees * cart_item.quantity)
        #     counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')
def cart_book(request):
    return render(request,"book.html")

schoolstore/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;1,300&display=swap' %}" rel="stylesheet">    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <style>
        body{background-color: #004466;}
    </style>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>

</div>

</body>
</html>

schoolstore/templates/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body{background-color:cyan;
             margin-top:250px;
             margin-left:400px;}
    </style>

</head>
<body>
<h1><em>Congrats...Your Order for Seat is placed<br>
          All the Best for your Carrier...</em></h1>
</body>
</html>

schoolstore/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

       This is the Booking page.Proceed to review your courses and place the order.........
{% endblock %}
{% block title %}
   College-Store
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class text="center">
        <br>
        <h1 class="text-center my_title">
            Currently No seats available
        </h1>
        <p class="text-center">
            Please Click<a href="{% url 'schoolapp:allStream' %}">Here</a>to book your seats.
        </p>
    </div>
</div>
 {% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Booking Site
        </h1>
        <br>

    </div>

    <div class="mx-auto">
       <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
         <table class="table my_custom_table">
          <thead class="my _custom_thead">
            <tr>
              <th colspan="5">
                Your Selected Course
              </th>
            </tr>
          </thead>
<!--        <tbody>-->
<!--        {% for cart_item in cart_items %}-->
<!--        <tr>-->
<!--            <td>-->
<!--                <a href="cart_item.product.get_absolute_url"><img style="width:100px;height:100px;" src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a>-->
<!--            </td>-->
<!--            <td class="text-left">-->
<!--                {{cart_item.product.name}}-->
<!--                <br>-->
<!--                SKU: {{cart_item.product.id}}-->
<!--                <br>-->
<!--                price: ${{cart_item.product.fees}}-->
<!--                <br>-->
<!--                Qty: {{cart_item.quantity}} X $ {{cart_item}}-->

<!--            </td>-->
<!--            <td>-->
<!--                $ {{cart_item.total}}-->
<!--            </td>-->
<!--            {% if cart_item.quantity < cart_item.product.seats %}-->
<!--            <td>-->
<!--                <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>-->
<!--                &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>-->
<!--                &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>-->
<!--            </td>-->
<!--            {% else %}-->

<!--            <td>-->
<!--                &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>-->
<!--                &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>-->
<!--            </td>-->
<!--   {% endif %}-->
<!--        </tr>-->

        {% endfor %}
<!--        </tbody>-->
<!--        </table>-->
<!--    </div>-->
<!--    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">-->
<!--        <table class="table my_custom_table">-->
<!--            <thead class="my_custom_thead">-->
<!--            <tr>-->
<!--                <th>-->
<!--                    Checkout-->
<!--                </th>-->
<!--            </tr>-->
<!--            </thead>-->
<!--            <tbody>-->
<!--            <tr>-->
<!--                <td>-->
<!--                    Please review your shopping cart items before proceeding with the order payment.-->
<!--                </td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <td class="text-left">-->
<!--                      Your Totalfees is: <strong>{{ total }}</strong>-->
<!--                </td>-->
<!--            </tr>-->
<!--            </tbody>-->

<!--        </table>-->
<!--        <div class="mx-auto">-->
<!--            <a href="{% url 'schoolapp:allStream' %}" class="btn btn-secondary btn-block my_custom_button">Visit Again</a>-->
<!--        </div>-->



<!--{% endif %}-->

<!--    </div>-->
<!--</div>-->
<!--</div>-->

{% endblock %}

schoolstore/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>form filling here</title>
    <style>
        body{background-color:#ff8080;}
    </style>


</head>
<body>
<h2 style="margin-left:450px;margin-top:100px;">Registration Form</h2>
<form style="margin-left:450px;" action="{% url 'dropdownapp:getdata' %}" method="post">
    {% csrf_token %}
    <label>Username:</label><br>
    <input type="text" name="username" placeholder="Enter your UserName"><br>
    Name:<br><input type="text" name="name" placeholder="Enter yourName"><br>
    DOB:<br><input  type="date" name="date" placeholder="Enter your DOB"><br>
    Age:<br><input type="text" name="age" placeholder="Enter your Age"><br>
    Gender:<br><input type="text" name="gender" placeholder="Enter your Gender"><br>

<label>
Phone number :<br>
</label>
<input type="text" name="country code" placeholder="Country Code"  value="+91" size="2"/>
<input type="text" name="phone" placeholder="phone no." size="10"/ required><br>
    email:<br><input type="email" name="email" placeholder="Enter your Mail Id"><br>
    ADDRESS:<br>
<textarea cols="80" rows="5" placeholder="Enter your Address" value="address" required>
</textarea><br>
    password:<br><input type="text" name="password" placeholder="Enter Password"><br>
   confirm password:<br> <input type="text" name="password1" placeholder="Enter confirm password"><br>
<!--    <input type="text" name="COURSES" placeholder="Courses"><br>-->
    Materials provide:<br>
    Note Book:<input type="checkbox" name="MATERIALS PROVIDE" placeholder="Materials Provide"><br>
    Pen:<input type="checkbox" name="MATERIALS PROVIDE" placeholder="Materials Provide"><br>
    Exam Papers:<input type="checkbox" name="MATERIALS PROVIDE" placeholder="Materials Provide"><br>
    Study Materials:<input type="checkbox" name="MATERIALS PROVIDE" placeholder="Materials Provide"><br>

    Department:<br><select  name="department" id="department" >
             <option value="" selected="selected">---Select Department---</option>
             <option value="Course">Courses</option>
             <option value="Biology Science" >Biology Science</option>
             <option value="Computer Science">Computer Science</option>
             <option value="Commerce">Commerce</option>
             <option value="Economics">Economics</option>
             <option value="Humanities">Humanities</option>
                    </select><br><br>
    Courses:<br><select name="courses" id="courses">

           </select>


  <br><br>
    <input type="submit" name="Submit & Logout">
 </form>








</body>
</html>

schoolstore/templates/dropdown.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration form filling</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        body{background-color:#ff8080;}
    </style>
</head>
<body>
<h2 style="margin-left:450px;margin-top:100px;">Registration Form</h2>
<form style="margin-left:450px;" action="{% url 'loginapp:order' %}" method="post">
    {% csrf_token %}
    <label>USERNAME:</label><br>
    <input type="text" name="username" placeholder="Enter your UserName"><br>
    <label>NAME:</label><br><input type="text" name="name" placeholder="Enter yourName"><br>
    <label>DOB:</label><br><input  type="date" name="date" placeholder="Enter your DOB"><br>
    <label>AGE:</label><br><input type="text" name="age" placeholder="Enter your Age"><br>
   <label> GENDER:</label><br><input type="text" name="gender" placeholder="Enter your Gender"><br><BR>

<label>
PHONE NUMBER :
</label>
<input type="text" name="country code" placeholder="Country Code"  value="+91" size="2"/>
<input type="text" name="phone" placeholder="phone no." size="10"/ required><br>
   <label> MAIL ID:</label><br><input type="email" name="email" placeholder="Enter your Mail Id"><br>
    <label>ADDRESS:</label><br>
<textarea cols="80" rows="5" placeholder="Enter your Address" value="address" style="width:550px;" required>
</textarea><br>
    <label>PASSWORD:</label><br><input type="text" name="password" placeholder="Enter Password"><br>
   <label>CONFIRM PASSWORD:</label><br> <input type="text" name="password1" placeholder="Enter confirm password"><br>
<!--    <input type="text" name="COURSES" placeholder="Courses"><br>-->




<!--  <div class="container">-->
<!--  <div class="card body">-->
<!--    <br/>-->
<!--    <br/>-->
<!--    <br/>-->


    <b>DEPARTMENT:</b><br>
        <select name="dept" id="Department" class="form-control" style="width:550px;">
            <option value="0">--Select Department--</option>
            {% for item in Department  %}
            <option value="{{ item.id }}">{{ item.departmentname }}</option>
            {% endfor %}
        </select>
    <br/>
    <b>COURSE:</b>
        <select name="course" id="Course" class="form-control" style="width:550px;">
            <option value="0">--Select Course--</option>
            {% for item in Course  %}
            <option value="{{ item.deptid_id }}">{{ item.coursename }}</option>
            {% endfor %}
        </select><br>

    <b>PURPOSE:</b><br>
    <select name="course" id="purpose" class="form-control" style="width:550px;">
            <option value="0">--Select Purpose--</option>
            <option>For Enquiry</option>
            <option>Place Order</option>
            <option>Return</option>
            <option>Admission Details</option>
            <option></option>

        </select><br>

    <b>MATERIALS PROVIDE:</b><br>
    Note Book:<input type="checkbox" name="MATERIALS PROVIDE" placeholder="Materials Provide"><br>
    Pen:<input type="checkbox" name="MATERIALS PROVIDE" placeholder="Materials Provide"><br>
    Exam Papers:<input type="checkbox" name="MATERIALS PROVIDE" placeholder="Materials Provide"><br>
    Study Materials:<input type="checkbox" name="MATERIALS PROVIDE" placeholder="Materials Provide"><br><br>
       <input type="submit" name="Submit & Logout">
</form>
    <br>
    <br>
    <br>
    <br>
    <br>


<!--   </div>-->

<!--</div>-->




<script>

$(document).ready(function(){

 var Department = $("#Department");
 var Course = $("#Course");
 var $options = Course.find('option');
 Department.on('change',function(){
    Course.html($options.filter('[value="'+ this.value  +'"]'));
 }).trigger('change');


});
</script>
</body>
</html>

schoolstore/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer" style="width:1245px; height:50px;">
  <p style="width:500px;">&copy; College-store tech private Ltd.All rights Reserved</p>
</div>

schoolstore/templates/header.html
{% load static %}
<header>
    <center>
        <img style="width:150px;height:150px;" src="{% static 'image/logo.png' %}" alt="logimage">
    </center>
</header>

schoolstore/templates/loggedin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>loggedin</title>
  <style>
    body{
         background-color:#bf80ff;}
  </style>
</head>
<body>
<h2> You are Successfully Logged In...Congratzz</h2>
<form action="{% url 'dropdownapp:getdata' %}" method="get">
    {% csrf_token %}
<!--        <input class="form-control me-2" type="search" placeholder="login" name="q" aria-label="login">-->

    <button type="submit" >Click Here</button>
</form>


</body>
</html>

schoolstore/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
    <style>
        body{background-color:#e6004c;}
    </style>
</head>
<body>
<h2  style="margin-left:450px;margin-top:200px;">Login Details</h2>
<form style="margin-left:450px;" action="login" method="post">
    {% csrf_token %}
    <input style="background-color:#ff9999;" type="text" name="username" placeholder="Enter your Username"><br>
    <input style="background-color:#ff9999;" type="password" name="password" placeholder="Enter your password"><br>

    <input style="background-color:#ff9999;" type="submit" ><br>
    <a href="{% url 'loginapp:register' %}">Register link</a>

</form>

</body>
</html>

schoolstore/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">




          <li class="nav-item">
                  <h1 style="color:black;font-size:20px;">
          <a class="nav-link" href="#">Registration</a>
                  <h1>
        </li>

        <li class="nav-item dropdown {% if 'schooapp' in request.path %} active {% endif %}">

          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <h1 style="font-size:20px;font-color:black;"> Department</h1>
          </a>

          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'schoolapp:allStream' %}">Courses</a></li>
            {% for cat in links %}
            <li>

                <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>

            </li>

            {% endfor %}

          </ul>
        </li>
  </ul>

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
             <h1 style="color:black;font-size:20px;">
                <a class="nav-link" href="#">Login</a>
             </h1>
        </li>
        </ul>
        <form class="d-flex" action="{% url 'schoolapp:login' %}" method="get">
        {% csrf_token %}
<!--        <input class="form-control me-2" type="search" placeholder="login" name="q" aria-label="login">-->
        <button class="btn btn-outline-success" type="submit"></button>
      </form>

    </div>
  </div>
</nav>

schoolstore/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="width:1245px;">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <a class="nav-link" href="{% url 'loginapp:login' %}">Login</a>
          </li>

          <li class="nav-item">
          <a class="nav-link" href="{% url 'loginapp:register' %}">Registration</a>
        </li>
        <li class="nav-item dropdown {% if 'search_app' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Department
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <div >
          {% for product in products.object_list %}

               <div>
                   <a href="{{product.get_url}}"><h6>{{product.name}}</h6></a>



<!--                    <p>{{product.fees}}</p>-->

               </div>

           {% endfor %}
     </div>

          </ul>
        </li>
<!--        {% if item_count > 0 %}-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link " href="{% url 'cart:cart_detail' %}" ><i class="fa fa-shopping-cart" ></i>({{item_count}})</a>-->
<!--        </li>-->
<!--        {% endif %}-->
  </ul>

      <form class="d-flex" action="{% url 'loginapp:login' %}" method="get">
        {% csrf_token %}
<!--        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">-->
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i>Login here</button>
      </form>
    </div>
  </div>
</nav>

schoolstore/templates/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>order confirmation</title>
</head>
<body style="background-color:#99ffff;">
<h3 style="margin-top:200px;margin-left:400px;"> Your Order is Confirmed..Congratulations..!!!</h3>

<a style="margin-top:200px;margin-left:500px;text-size:20px;" href="/">Home Page</a>

</body>
</html>

schoolstore/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        input{background-color:#1BECC9;}
        body{background-color:#EC1B57;}
    </style>
</head>
<body>
<!--Test Register-->
<h2 style="margin-left:450px;margin-top:100px;">Registration Form</h2>
<form style="margin-left:450px;" action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="UserName"><br>
    <input type="text" name="first_name" placeholder="Enter your Firstname"><br>
    <input type="text" name="last_name" placeholder="Enter your Lastname"><br>
    <input type="email" name="email" placeholder="Enter your Email Address"><br>
    <input type="password" name="password" placeholder="Enter your Password"><br>
    <input type="password" name="password1" placeholder="Confirm your Password"><br>
   <input type="submit" >
</form>
{% for msg in messages %}
{{msg}}
{% endfor %}

</body>
</html>

schoolstore/templates/stream.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     {% if stream %}
          {{ stream.description|truncatewords:155 }}
     {% else %}
          Welcome to the world of knowledge.....
     {% endif %}
{% endblock %}

{% block title %}
{% if stream %}
          {{stream.name}}--College Store
{% else %}
          See our courses
{% endif %}
{% endblock %}
{% block content %}
{% if category %}
<div>
     <div class="row my_row_class">
         <div class="mx_auto">
             <p><a href="{% url 'schoolapp:allStream' %}">OUR COURSES</a></p>
     </div>
          </div>
</div>
{% endif %}
<div class="mx_auto">
     {% if category %}
     <img class="my_image" style="width:150px;height:200px;" src="{{stream.image.url}}" alt="{{stream.name}}">
</div>
<br>
<div>
     <h1 class="text-center my_title">{{stream.name}}</h1>
     <p class="text-justify">{{stream.description}}</p>
</div>
{% else %}
<div>
<img class="my_image my_image_padding" style="width:1250px;height:500px;" src="{% static 'image/banner.jpg' %}" alt="Our courses">
</div>
<br>
<div>
     <h1 class="text_center my_title">Our College-store </h1>
     <p class="text-justify">It is my great pleasure to welcome you to this College  website hoping you will find it informative.


 In this College, we are striving to achieve our vision of being an outstanding educational and research college serving the needs of our country and addressing the challenges faced by the society. This College  is among the first-ranked Colleges.  </div>
{% endif %}
<div class="container" >
<!--     <div class="row mx_auto">-->
<!--          {% for product in products.object_list %}-->
<!--           <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4">-->
<!--               <div class="card text-center" style="min-width:18rem;">-->
<!--                   <a href="{{product.get_url}}"><img class="card-img-top my_image" style="width:150px;height:150px;" src="{{product.image.url}}" alt="{{product.name}}"></a>-->

<!--                <div class="card-body">-->
<!--                    <h4>{{product.name}}</h4>-->
<!--&lt;!&ndash;                    <p>{{product.fees}}</p>&ndash;&gt;-->
<!--                    </div>-->
<!--               </div>-->
<!--            </div>-->
<!--           {% endfor %}-->
<!--     </div>-->
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
         {% for pg in products.paginator.page_range %}
          <a href="?page={{pg}}" class= "btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
    </div>
{% endif %}
    </div>
    <br>
</div>

{% endblock %}